Portfolio: setup and mobile first
RashidMenhas/My-Portfolio pull request #1
Opened 2022-08-18 23:13 UTC by RashidMenhas

- Add the headline section (right after the header):
- Add The 2 sections you need to build for this project are:
the toolbar (or header):

2022-08-19 01:05 UTC, roshan-bajgain requested changes
Hi @RashidMenhas, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 01:05 UTC, roshan-bajgain commented on index.html
> +    </header>
- [ ] Kindly wrap this section with a section tag for better semantic HTML, the header tag should close after the </nav> tag and the remaining are section tag.

2022-08-19 01:05 UTC, roshan-bajgain commented on index.html
> +            Glad to see you!</h1>
- [ ] If you see the design then the h1 tag has a different color. kindly use `color: #172B4D;` and increase the font-weight so It matches the design

2022-08-19 01:05 UTC, roshan-bajgain commented on index.html
> +        <p class="description">I’m a software developer! I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project y
- [ ] You have implemented all the project requirements it would be nicer if you use `color: #344563;` in your description. Besides this everything is fine

2022-08-19 01:05 UTC, roshan-bajgain commented on style.css
> +}
- [ ] You have a proper background image the only thing you need to work on is to adjust the image as some of the portion is not showing in the mobile version. Please fix it
### Figma design
![fffffffffff](https://user-images.githubusercontent.com/81727988/185519667-1a277953-a4d0-45c7-bbe1-b55af865fc39.png)
### Your design
![hhhhhhhhhhhhh](https://user-images.githubusercontent.com/81727988/185519771-76f5f040-9683-4303-9ad6-cd15d6a3f785.png)

2022-08-19 01:05 UTC, roshan-bajgain commented on index.html
> +        <h5 class="btn-connect">LET’S CONNECT</h5>
- [ ] The heading is perfectly fine the only thing left is font-size So I would suggest you increase the size so It fit the content. let's increase it and make font-size: 19px;

2022-08-20 11:39 UTC, emmiiorji approved these changes
Hi @RashidMenhas, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![goodjob-slowclap](https://user-images.githubusercontent.com/20554583/185743496-0d1eab39-ada8-4d44-bf7f-20e140cda80a.gif)


## Good Highlights ✅
- You have implemented the requested changes
- Good commit messages
- Good use of GitHub flow

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 11:39 UTC, emmiiorji commented on README.md
> +_NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setti
[Optional] I suggest that you remove this note from the README file. It's only a note to you (the author) not to your audience. By doing so, your documentation will be more professional and concise.

2022-08-20 17:42 UTC, merged