Add a contact form and finish the mobile version
RashidMenhas/My-Portfolio pull request #3
Opened 2022-08-24 15:53 UTC by RashidMenhas

- Add a contact form to my portfolio.
- Name field accepts up to 30 chars.
- Email field accepts only emails.
- The message field accepts up to 500 chars.
- All fields have placeholder text.
- All fields have the correct type.
- A user cannot submit the form if one or more of the fields is empty.

2022-08-24 16:18 UTC, mugishasam123 requested changes
Hi @RashidMenhas  👋 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![alt](https://c.tenor.com/0Q8SiDHvSZIAAAAC/so-close-so-close-seth-meyers.gif)
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- No linter errors 👍 
- Good commit messages ✔️ 
- Descriptive PR , keep rocking 🚀 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 16:18 UTC, mugishasam123 commented on index.html
> +    <footer class="footer-form">
- [ ] Kindly you should try to stick to the design as much as possible to match the Figma design, so please work on the spacing between the form and about section to make it match the Figma design. you got this 👍 

Figma design:
![image](https://user-images.githubusercontent.com/90524466/186469776-4936cbb2-c579-4056-8596-c3c430300f60.png)

Your design:
![image](https://user-images.githubusercontent.com/90524466/186469918-d3a972fe-9bba-4a02-8c08-9177f33c00aa.png)

2022-08-24 20:23 UTC, mugishasam123 approved these changes
Hi @RashidMenhas  👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors 👍 
- Nice use of git-flow ✔️ 
- Good commit messages ✔️ 
## Optional suggestions
- N/A
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-25 05:13 UTC, merged

2022-08-30 09:53 UTC, Bondok6 reviewed
# STATUS: APPROVED :green_circle: :clap: 

## Hi Team, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

TO HIGHLIGHT:

- Your project is professional ✅
- Your repo is professional ✅


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

<img src="https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966" />

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._